"""empty message

Revision ID: e92236051eee
Revises: 9ae837b2de75
Create Date: 2021-03-10 09:58:31.699628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92236051eee'
down_revision = '9ae837b2de75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=False),
    sa.Column('for_who', sa.Integer(), nullable=False),
    sa.Column('for_who_type', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_token')
    # ### end Alembic commands ###
