"""empty message

Revision ID: c14f69e1bdc3
Revises: e92236051eee
Create Date: 2021-03-10 10:15:52.415543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14f69e1bdc3'
down_revision = 'e92236051eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_token_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('for_who', sa.Integer(), nullable=False),
    sa.Column('for_who_type', sa.String(length=6), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('validation_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_value', sa.DATE(), nullable=False),
    sa.Column('for_who', sa.INTEGER(), nullable=False),
    sa.Column('for_who_type', sa.VARCHAR(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('validation_token_record')
    # ### end Alembic commands ###
